name: Welcome
version: '${version}'
main: com.welcome.WelcomePlugin
api-version: 1.21
authors: [YourName]
description: A welcome plugin for your server.

commands:
  welcome:
    description: Main welcome voting command
    usage: /welcome <player>
    permission: welcome.use

permissions:
  welcome.use:
    description: 允許使用 /welcome 指令
    default: true
  welcome.admin:
    description: 允許使用所有管理指令
    default: op
